#!/bin/bash
#===============================================================================
# Copyright (C) 2018 Albert Steiner
# Author: Albert Steiner albert@alst.ovh
# 28/01/2018
#
# This file is free software you can redistribute it and/or modify
# it under the terms of the GNU General Public License (GPL)
# as published by the Free Software Foundation, in version 2
# It is distributed in the  hope that it will be useful,
# but WITHOUT ANY WARRANTY of any kind.
#===============================================================================

USER=`whoami`
VBOXMANAGE="/usr/local/bin/vboxmanage"
VBOXSLEEP="10"
VBOXWAIT="0"
VBOXMAXWAIT="90"
LOGFILEPATH="VBPATH"
VBOXVMSCONFIGPATH="/Users/VBOXUSER/.config/vbox"
if [ ! -z "$(which mcedit)" ]; then
  VBOXEDITOR="mcedit"
else
  VBOXEDITOR="nano"
fi
ask() {
  local prompt default reply

  while true; do

    if [ "${2:-}" = "Y" ]; then
      prompt="Y/n"
      default=Y
    elif [ "${2:-}" = "N" ]; then
      prompt="y/N"
      default=N
    else
      prompt="y/n"
      default=
    fi

    # Ask the question (not using "read -p" as it uses stderr not stdout)
    echo "$1 [$prompt] "

    # Read the answer (use /dev/tty in case stdin is redirected from somewhere else)
    read reply </dev/tty

    # Default?
    if [ -z "$reply" ]; then
      reply=$default
    fi

    # Check if the reply is valid
    case "$reply" in
      Y*|y*) return 0 ;;
      N*|n*) return 1 ;;
    esac

  done
}

#===============================================================================
# End
#===============================================================================
